spring:
  application:
    name: fregrance
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fregrance?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:fregrance_user}
    password: ${SPRING_DATASOURCE_PASSWORD:proclimb}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
