spring:
  application:
    name: fregrance
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    root: INFO
